name: Generate Static Site Artifact from .ipynb files
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Generate Files from MD
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Check out repo
        uses: actions/checkout@v1 
      - name: Generate Vault Pass for Ansible 
        run: echo '${{ secrets.VaultPass }}' >> ~/.vault_pass
      - name: Run docker + build script
        run: make run-app env=dev 
      - name: GitHub Pages Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GithubToken }}
