name: Create and Deploy Artifact 
on: 
  push:
    branches:
      - master
    paths:
      - 'content/**'
      - '!content/psets/**'
      - '!content/raw_data/**'
jobs:
  build:
    name: Generate and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v1 

      - name: Generate Vault Pass for Ansible 
        run: echo '${{ secrets.VaultPass }}' >> ~/.vault_pass

      - name: Run docker + build script
        run: make run-app env=dev 

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: static 
        env:
          GITHUB_TOKEN: ${{ secrets.GithubToken }}
